version: '3.9'
services:
  server:
      container_name: server
      build: 
        context: .
        dockerfile: Docker/Dockerfile.dev
      volumes: 
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - ${APP_PORT}:${APP_PORT}
      command: npm run start:dev
      
